-- Full schema for tcatweb database

CREATE TABLE IF NOT EXISTS images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(512) NOT NULL,
    alt TEXT,
    uploadedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS question_bank (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type ENUM('standard', 'image', 'match', 'multiple') NOT NULL DEFAULT 'standard',
    prompt TEXT NOT NULL,
    options JSON,
    correctOption TINYINT,
    correctOptions JSON,
    imageId INT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (imageId) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS match_pairs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    questionBankId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    imageId INT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (questionBankId) REFERENCES question_bank(id) ON DELETE CASCADE,
    FOREIGN KEY (imageId) REFERENCES images(id)
);

CREATE TABLE IF NOT EXISTS quizzes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    durationMinutes INT NOT NULL DEFAULT 30,
    quizCode VARCHAR(64) NOT NULL UNIQUE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quizId INT NOT NULL,
    prompt TEXT NOT NULL,
    options JSON NOT NULL,
    correctOption TINYINT NOT NULL CHECK (correctOption BETWEEN 0 AND 3),
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (quizId) REFERENCES quizzes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS grades (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quizId INT NOT NULL,
    studentName VARCHAR(255) NOT NULL,
    score FLOAT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (quizId) REFERENCES quizzes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS classroom_netmap (
    id INT AUTO_INCREMENT PRIMARY KEY,
    block_index INT NOT NULL,
    vlan VARCHAR(16) NOT NULL,
    switchName VARCHAR(64) NOT NULL,
    portNumber VARCHAR(32) NOT NULL,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subject VARCHAR(255) NOT NULL,
    breakDown TEXT NOT NULL,
    resolution TEXT,
    teamLeader VARCHAR(255) NOT NULL,
    teamMembers TEXT NOT NULL,
    status ENUM('open', 'in_progress', 'resolved', 'closed') NOT NULL DEFAULT 'open',
    creationDate DATETIME NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quiz_attempts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    quizId INT NOT NULL,
    quizCode VARCHAR(64) NOT NULL,
    participantName VARCHAR(255) NOT NULL,
    participantKey VARCHAR(255) NOT NULL,
    startedAt DATETIME NOT NULL,
    expiresAt DATETIME NOT NULL,
    isCompleted BOOLEAN NOT NULL DEFAULT FALSE,
    completedAt DATETIME,
    score FLOAT,
    totalQuestions INT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (quizId) REFERENCES quizzes(id) ON DELETE CASCADE
);
